(deftheme xin-ample
  "Created 2016-01-15.")

(custom-theme-set-variables
 'xin-ample
 '(ansi-color-names-vector ["#454545" "#cd5542" "#6aaf50" "#baba36" "#5180b3" "#ab75c3" "#bdbc61" "#bdbdb3"]))

(custom-theme-set-faces
 'xin-ample
 '(cursor ((t (:foreground "gray13" :background "#f57e00"))))
 '(fringe ((t (:background "#393939"))))
 '(link ((t (:foreground "#68a5e9" :underline t))))
 '(region ((t (:background "#303030"))))
 '(font-lock-builtin-face ((t (:foreground "#528fd1"))))
 '(font-lock-comment-face ((t (:foreground "#757575"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#656565"))))
 '(font-lock-function-name-face ((t (:foreground "#6aaf50"))))
 '(font-lock-keyword-face ((t (:foreground "#5180b3"))))
 '(font-lock-string-face ((t (:foreground "#bdbc61"))))
 '(font-lock-preprocessor-face ((t (:foreground "#dF9522"))))
 '(font-lock-type-face ((t (:foreground "violet"))))
 '(font-lock-constant-face ((t (:foreground "#ab75c3"))))
 '(font-lock-warning-face ((t (:foreground "red" :bold t))))
 '(font-lock-variable-name-face ((t (:foreground "#baba36"))))
 '(font-lock-doc-face ((t (:foreground "tomato"))))
 '(powerline-active1 ((t (:background "#252525" :foreground "cornsilk4"))))
 '(powerline-active2 ((t (:background "cornsilk4" :foreground "#252525"))))
 '(powerline-inactive1 ((t (:background "gray13" :foreground "cornsilk4"))))
 '(powerline-inactive2 ((t (:background "#454545" :foreground "cornsilk4"))))
 '(mode-line-inactive ((t (:background "#454545" :foreground "cornsilk4"))))
 '(mode-line ((t (:background "cornsilk4" :foreground "#252525"))))
 '(linum ((t (:background nil :foreground "#757575"))))
 '(popup-tip-face ((t (:background "#bdbdb3" :foreground "gray13"))))
 '(header-line ((t (:background "#bdbdb3" :foreground "gray13"))))
 '(button ((t (:foreground "#68a5e9" :background nil :underline t))))
 '(isearch ((t (:background "#5180b3" :foreground "gray13"))))
 '(lazy-highlight ((t (:background "gray13" :foreground "#ab75c3" :underline t))))
 '(vertical-border ((t (:background "#454545" :foreground "#252525"))))
 '(highlight-indentation-face ((t (:background "gray16"))))
 '(minibuffer-prompt ((t (:foreground "#fffe0a" :bold t :background nil))))
 '(compilation-error ((t (:foreground "#cd5542" :bold t))))
 '(compilation-warning ((t (:foreground "#dF9522" :bold t))))
 '(compilation-info ((t (:foreground "#6aaf50" :bold t))))
 '(comint-highlight-prompt ((t (:foreground "#6aaf50"))))
 '(undo-tree-visualizer-active-branch-face ((t (:inherit default))))
 '(undo-tree-visualizer-default-face ((t (:inherit font-lock-comment-face))))
 '(undo-tree-visualizer-register-face ((t (:foreground "#baba36" :background nil))))
 '(undo-tree-visualizer-current-face ((t (:foreground "#cd5542" :background nil))))
 '(undo-tree-visualizer-unmodified-face ((t (:foreground "#ab75c3" :background nil))))
 '(show-paren-match ((t (:foreground nil :background "#656565"))))
 '(show-paren-mismatch ((t (:inherit error))))
 '(error ((t (:foreground "red"))))
 '(ido-only-match ((t (:foreground "#6aaf50"))))
 '(ido-first-match ((t (:foreground "#5180b3"))))
 '(ido-incomplete-regexp ((t (:foreground "#cd5542"))))
 '(ido-subdir ((t (:foreground "#baba36"))))
 '(helm-M-x-key ((t (:foreground "#dF9522" :underline nil))))
 '(helm-candidate-number ((t (:foreground "#6aaf50" :background "#454545"))))
 '(helm-ff-directory ((t (:foreground "#5180b3"))))
 '(helm-ff-executable ((t (:foreground "#6aaf50"))))
 '(helm-ff-file ((t (:inherit default))))
 '(helm-ff-prefix ((t (:foreground "#cd5542"))))
 '(helm-header ((t (:foreground "gray13" :background "#bdbdb3"))))
 '(helm-match ((t (:foreground "#5180b3" :background "#252525"))))
 '(helm-selection ((t (:foreground "#baba36" :background "#303030" :bold t))))
 '(helm-source-header ((t (:foreground "#252525" :background "#5180b3"))))
 '(ac-candidate-face ((t (:foreground "black" :background "#bdbdb3"))))
 '(ac-selection-face ((t (:foreground "#bdbdb3" :background "#5180b3"))))
 '(ac-candidate-mouse-face ((t (:inherit ac-selection-face))))
 '(ac-completion-face ((t (:inherit font-lock-comment-face :underline t))))
 '(company-preview-common ((t (:inherit font-lock-comment-face))))
 '(company-scrollbar-bg ((t (:foreground nil :background "#252525"))))
 '(company-scrollbar-fg ((t (:foreground nil :background "#656565"))))
 '(company-tooltip ((t (:foreground "gray13" :background "#bdbdb3"))))
 '(company-tooltip-common ((t (:foreground "#5180b3" :background "#bdbdb3"))))
 '(company-tooltip-common-selection ((t (:foreground "gray13" :background "#5180b3"))))
 '(company-tooltip-mouse ((t (:foreground nil :background "#528fd1"))))
 '(company-tooltip-selection ((t (:foreground "#bdbdb3" :background "#5180b3"))))
 '(org-done ((t (:foreground "#6aaf50" :background nil))))
 '(org-todo ((t (:foreground "#cd5542" :background nil))))
 '(org-hide ((t (:foreground "gray13" :background nil))))
 '(highlight-indentation-current-column-face ((t (:foreground nil :background "#757575"))))
 '(highlight-indentation-face ((t (:foreground nil :background "#252525"))))
 '(trailing-whitespace ((t (:background "white" :bold t))))
 '(custom-button ((t (:foreground nil :background nil))))
 '(custom-button-mouse ((t (:foreground nil :background nil))))
 '(custom-button-pressed ((t (:foreground nil :background nil))))
 '(custom-button-pressed-unraised ((t (:foreground "#ab75c3" :background nil))))
 '(custom-button-unraised ((t (:foreground nil :background nil))))
 '(custom-changed ((t (:foreground "#cd5542" :background nil))))
 '(custom-comment ((t (:foreground "gray13" :background "#baba36"))))
 '(custom-comment-tag ((t (:foreground "#bdbdb3" :background nil))))
 '(custom-documentation ((t (:foreground nil :background nil))))
 '(custom-face-tag ((t (:foreground "#528fd1" :background nil))))
 '(custom-group-subtitle ((t (:foreground nil :background nil :bold t))))
 '(custom-group-tag ((t (:foreground "#528fd1" :background nil :bold t))))
 '(custom-group-tag-1 ((t (:foreground "#baba36" :background nil :bold t))))
 '(custom-invalid ((t (:foreground "gray13" :background "#cd5542"))))
 '(custom-link ((t (:inherit button))))
 '(custom-modified ((t (:foreground "#cd5542" :background nil))))
 '(custom-rogue ((t (:foreground "#baba36" :background "gray13"))))
 '(custom-saved ((t (:foreground nil :background nil :underline t))))
 '(custom-set ((t (:foreground "#bdbdb3" :background "#656565"))))
 '(custom-state ((t (:foreground "#6aaf50" :background nil))))
 '(custom-themed ((t (:foreground "#cd5542" :background nil))))
 '(custom-variable-button ((t (:foreground nil :background nil :underline t :bold t))))
 '(custom-variable-tag ((t (:foreground "#528fd1" :background nil :bold t))))
 '(custom-visibility ((t (:inherit button))))
 '(neo-banner-face ((t (:foreground "#528fd1" :background nil :bold t))))
 '(neo-button-face ((t (:foreground nil :background nil))))
 '(neo-dir-link-face ((t (:foreground "#5180b3" :background nil))))
 '(neo-expand-btn-face ((t (:foreground "#bdbdb3" :background nil))))
 '(neo-file-link-face ((t (:foreground "#bdbdb3" :background nil))))
 '(neo-header-face ((t (:foreground "#bdbdb3" :background nil))))
 '(neo-root-dir-face ((t (:foreground "#6aaf50" :background nil :bold t))))
 '(neo-vc-added-face ((t (:foreground "#6aaf50" :background nil))))
 '(neo-vc-conflict-face ((t (:foreground "#dF9522" :background nil))))
 '(neo-vc-default-face ((t (:foreground "#bdbdb3" :background nil))))
 '(neo-vc-edited-face ((t (:foreground "#baba36" :background nil))))
 '(neo-vc-ignored-face ((t (:foreground "#656565" :background nil))))
 '(neo-vc-missing-face ((t (:foreground "#cd5542" :background nil))))
 '(neo-vc-needs-merge-face ((t (:foreground "#dF9522" :background nil))))
 '(neo-vc-needs-update-face ((t (:foreground nil :background nil :underline t))))
 '(neo-vc-removed-face ((t (:foreground "#ab75c3" :background nil))))
 '(neo-vc-unlocked-changes-face ((t (:foreground "#cd5542" :background "Blue"))))
 '(neo-vc-unregistered-face ((t (:foreground nil :background nil))))
 '(neo-vc-up-to-date-face ((t (:foreground "#bdbdb3" :background nil))))
 '(widget-field ((t (:foreground "#bdbdb3" :background "#656565"))))
 '(default ((t (:background "#2e3436" :foreground "#bdbdb3")))))

(provide-theme 'xin-ample)
