(deftheme xin-material
  "Created 2016-01-15.")

(custom-theme-set-variables
 'xin-material
 '(ansi-color-names-vector ["#ffffff" "#f36c60" "#8bc34a" "#fff59d" "#4dd0e1" "#b39ddb" "#81d4fa" "#263238"])
 '(ansi-color-faces-vector [default bold shadow italic underline bold bold-italic bold]))

(custom-theme-set-faces
 'xin-material
 '(bold ((((class color) (min-colors 89)) (:weight bold))))
 '(bold-italic ((((class color) (min-colors 89)) (:slant italic :weight bold))))
 '(underline ((((class color) (min-colors 89)) (:underline t))))
 '(italic ((((class color) (min-colors 89)) (:slant italic))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#ff8A65"))))
 '(font-lock-comment-delimiter-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(font-lock-constant-face ((t (:foreground "#E6DB74" :weight bold))))
 '(font-lock-doc-face ((t (:foreground "tomato"))))
 '(font-lock-function-name-face ((t (:foreground "violet"))))
 '(font-lock-keyword-face ((t (:foreground "light sky blue" :weight bold))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(font-lock-preprocessor-face ((t (:foreground "maroon1"))))
 '(font-lock-regexp-grouping-backslash ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(font-lock-regexp-grouping-construct ((((class color) (min-colors 89)) (:foreground "#b39ddb"))))
 '(font-lock-string-face ((t (:foreground "#9ccc65"))))
 '(font-lock-type-face ((t (:foreground "deep sky blue"))))
 '(font-lock-variable-name-face ((t (:foreground "spring green"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:weight bold :foreground "#f36c60"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(success ((((class color) (min-colors 89)) (:foreground "SeaGreen2"))))
 '(error ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(flycheck-error ((((class color) (min-colors 89)) (:underline (:style wave :color "#f36c60")))))
 '(flycheck-warning ((((class color) (min-colors 89)) (:underline (:style wave :color "#ff9800")))))
 '(highlight-indentation-face ((t (:background "#37474f"))))
 '(highlight-indentation-current-column-face ((((class color) (min-colors 89)) (:background "#1c1f26"))))
 '(flymake-warnline ((((class color) (min-colors 89)) (:underline (:style wave :color "#ff9800") :background "#263238"))))
 '(flymake-errline ((((class color) (min-colors 89)) (:underline (:style wave :color "#f36c60") :background "#263238"))))
 '(match ((((class color) (min-colors 89)) (:foreground "#263238" :background "#8bc34a" :inverse-video nil))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#8bc34a"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:foreground "#263238" :background "#8bc34a" :inverse-video nil))))
 '(isearch-fail ((((class color) (min-colors 89)) (:background "#263238" :inherit font-lock-warning-face :inverse-video t))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#b39ddb"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(ido-indicator ((((class color) (min-colors 89)) (:foreground "#f36c60" :background "#263238"))))
 '(ido-virtual ((t (:foreground "#b0bec5"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#ff9800"))))
 '(fringe ((t (:background "#393939"))))
 '(linum ((t (:background "#2e3436" :foreground "#a7adba"))))
 '(border ((t (:background "#37474f"))))
 '(vertical-border ((t (:background "#555555" :foreground "#555555"))))
 '(highlight ((((class color) (min-colors 89)) (:inverse-video nil :background "#37474f"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#1c1f26"))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:foreground "#ffd700" :background nil :weight bold))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box nil :weight normal :background "#1c1f26" :foreground "#a7adba" :inherit mode-line))))
 '(mode-line-emphasis ((((class color) (min-colors 89)) (:foreground "#ffffff" :slant italic))))
 '(mode-line-highlight ((((class color) (min-colors 89)) (:foreground "#b39ddb" :box nil))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(region ((((class color) (min-colors 89)) (:background "#555555"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#bf616a"))))
 '(header-line ((((class color) (min-colors 89)) (:inherit mode-line :foreground "#b39ddb" :background nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:foreground "#f36c60" :inverse-video t :underline nil))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground "black" :background "#81d4fa" :inherit show-paren-match))))
 '(sp-show-pair-mismatch-face ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-match))))
 '(paren-face-mismatch ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(paren-face-no-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit show-paren-mismatch))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#8bc34a" :weight bold))))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) (:foreground "#8bc34a" :weight bold))))
 '(undo-tree-visualizer-active-branch-face ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(link ((((class color) (min-colors 89)) (:foreground nil :underline t))))
 '(widget-button ((((class color) (min-colors 89)) (:underline t :weight bold))))
 '(widget-field ((((class color) (min-colors 89)) (:background "#37474f" :box (:line-width 1 :color "#ffffff")))))
 '(compilation-column-number ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(compilation-line-number ((((class color) (min-colors 89)) (:foreground "#fff59d"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#263238"))))
 '(helm-match ((((class color) (min-colors 89)) (:foreground "gold1"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#81d4fa"))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#81d4fa"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#81d4fa" :underline t))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:foreground "#ffffff" :background "#ef6c00"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#455A64" :foreground "#eceff1" :height 1.3 :bold t))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:foreground "#ffffff" :weight bold))))
 '(which-key-special-key-face ((((class color) (min-colors 89)) (:foreground "#ff9800" :weight bold :height 1.1))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#ffffff"))))
 '(which-key-group-description-face ((((class color) (min-colors 89)) (:foreground "#81d4fa"))))
 '(which-key-separator-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:foreground "#81d4fa" :bold t))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#4dd0e1" :underline nil))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(org-agenda-dimmed-todo-face ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(org-block ((((class color) (min-colors 89)) (:foreground "#8bc34a" :background "#1c1f26"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#8bc34a" :background "#1c1f26"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#37474f"))))
 '(org-column-title ((((class color) (min-colors 89)) (:inherit org-column :weight bold :underline t))))
 '(org-date ((((class color) (min-colors 89)) (:foreground "#80cbc4" :underline t))))
 '(org-document-info ((((class color) (min-colors 89)) (:foreground "#81d4fa" :height 1.35))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#8bc34a" :height 1.35))))
 '(org-document-title ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :height 1.35))))
 '(org-done ((t (:foreground "#8bc34a" :weight bold))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(org-footnote ((((class color) (min-colors 89)) (:foreground "#81d4fa"))))
 '(org-formula ((((class color) (min-colors 89)) (:foreground "#f36c60"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#263238" :background "#263238"))))
 '(org-link ((((class color) (min-colors 89)) (:foreground "#4dd0e1" :underline t))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(org-scheduled-previously ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#b0bec5"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#e3f2fd" :background "#1c1f26"))))
 '(org-todo ((t (:foreground "maroon1" :weight bold))))
 '(org-upcoming-deadline ((((class color) (min-colors 89)) (:foreground "#ff9800"))))
 '(org-warning ((((class color) (min-colors 89)) (:weight bold :foreground "#f36c60"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:foreground "#b3e5fc" :background "#1e2930" :underline "#e1f5fe"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:foreground "#b3e5fc" :background "#1e2930" :overline "#e1f5fe"))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit outline-1 :overline "#b0bec5" :background "#455A64" :weight bold))))
 '(org-level-2 ((((class color) (min-colors 89)) (:foreground "burlywood" :inherit outline-2))))
 '(org-level-3 ((((class color) (min-colors 89)) (:inherit outline-3))))
 '(org-level-4 ((((class color) (min-colors 89)) (:inherit outline-4))))
 '(org-level-5 ((((class color) (min-colors 89)) (:inherit outline-5))))
 '(org-level-6 ((((class color) (min-colors 89)) (:inherit outline-6))))
 '(org-level-7 ((((class color) (min-colors 89)) (:inherit outline-7))))
 '(org-level-8 ((((class color) (min-colors 89)) (:inherit outline-8))))
 '(cfw:face-title ((((class color) (min-colors 89)) (:background "#263238" :foreground "#eceff1" :height 1.3 :weight bold))))
 '(cfw:face-today ((((class color) (min-colors 89)) (:background "#1c1f26" :foreground "#ffffff"))))
 '(cfw:face-day-title ((((class color) (min-colors 89)) (:background "#37474f" :foreground "#ffffff"))))
 '(cfw:face-today-title ((((class color) (min-colors 89)) (:background "#bf616a" :foreground "#ffffff"))))
 '(cfw:face-header ((((class color) (min-colors 89)) (:background "#37474f" :foreground "#ffffff"))))
 '(cfw:face-sunday ((((class color) (min-colors 89)) (:background "#37474f" :foreground "#81d4fa" :weight bold))))
 '(cfw:face-saturday ((((class color) (min-colors 89)) (:background "#37474f" :foreground "#81d4fa" :weight bold))))
 '(cfw:face-select ((((class color) (min-colors 89)) (:background "#555555" :foreground "#ffffff"))))
 '(cfw:face-toolbar ((((class color) (min-colors 89)) (:background "#81d4fa" :foreground "#263238" :weight bold))))
 '(cfw:face-toolbar-button-off ((((class color) (min-colors 89)) (:background "#81d4fa" :foreground "#263238" :weight bold))))
 '(cfw:face-toolbar-button-on ((((class color) (min-colors 89)) (:background "#81d4fa" :foreground "#bf616a" :weight bold))))
 '(cfw:face-holiday ((((class color) (min-colors 89)) (:background "#37474f" :foreground "#8bc34a" :weight bold))))
 '(company-preview-common ((((class color) (min-colors 89)) (:foreground "#C0C0C0" :background "#FFFFD7"))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#F0F0F0"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#C0C0C0"))))
 '(company-tooltip ((((class color) (min-colors 89)) (:weight bold :foreground "#1c1f26" :background "#78909c"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:weight normal :foreground "#b0bec5" :background "#78909c"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:weight normal :inherit company-tooltip-selection))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:weight bold :foreground "#ffffff" :background "#37474f"))))
 '(powerline-active1 ((t (:foreground "#ffffff" :background "#555555"))))
 '(powerline-active2 ((t (:foreground "#ffffff" :background "#78909c"))))
 '(powerline-inactive1 ((t (:foreground "#b0bec5" :background "#555555"))))
 '(powerline-inactive2 ((t (:foreground "#b0bec5" :background "#555555"))))
 '(outline-1 ((((class color) (min-colors 89)) (:inherit nil :foreground "#eceff1"))))
 '(outline-2 ((((class color) (min-colors 89)) (:inherit nil :foreground "#e1f5fe"))))
 '(outline-3 ((((class color) (min-colors 89)) (:inherit nil :foreground "#a5d6a7"))))
 '(outline-4 ((((class color) (min-colors 89)) (:inherit nil :foreground "#ffcc80"))))
 '(outline-5 ((((class color) (min-colors 89)) (:inherit nil :foreground "#b3e5fc"))))
 '(outline-6 ((((class color) (min-colors 89)) (:inherit nil :foreground "CadetBlue1"))))
 '(outline-7 ((((class color) (min-colors 89)) (:inherit nil :foreground "aquamarine1"))))
 '(outline-8 ((((class color) (min-colors 89)) (:inherit nil :foreground "#b39ddb"))))
 '(custom-variable-tag ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(custom-group-tag ((((class color) (min-colors 89)) (:foreground "#4dd0e1"))))
 '(custom-state ((((class color) (min-colors 89)) (:foreground "#8bc34a"))))
 '(default ((t (:background "#2e3436" :foreground "#d3d3d3")))))

(provide-theme 'xin-material)
